#!/bin/bash

echo 'Rebuilding Project' 
./buildProject

echo 'Starting tests: '
j=0
i=0

for n in $(seq 1 20); do
	((i++))
	if [ $((n % 10)) == 0 ]; then
		((j++))
		i=0
	fi
	
	if [ -f Posted-TestCases/$j$i/PJ3 ]; then
		rm Posted-TestCases/$j$i/PJ3
		echo 'Removed previous PJ3 build' 
	fi

	echo 'adding PJ3'
	cp PJ3 Posted-TestCases/$j$i

	if [ -f Posted-TestCases/$j$i/MyOutput.txt ]; then
		rm Posted-TestCases/$j$i/MyOutput.txt
	fi

	touch Posted-TestCases/$j$i/MyOutput.txt	

	cd Posted-TestCases/$j$i
	./Execution < Instructions > MyOutput.txt

	echo 'Test: test'$j$i
	diff -y Output.txt MyOutput.txt

	cd ../..

 	
done

echo 'Finished tests.'
